### PR TITLE
check rules and others

### PR DESCRIPTION
**Pull request by chenfengyuan**
changes:
1. check rules
2. change access log's level to debug
3. reformat code
sorry for reformatted code

### CODE REVIEW

**Comment by thinxer** [comment]
Thanks for the pull request. The code indeed has not been properly formatted to PEP8 at that time. In the meantime, the two introspection errors should be fixed (instead of simply silencing). I will be happy to have this merged.

**Comment by chenfengyuan** [comment]
hi, thanks for the reply. I removed the "no inspection" tag and some minor changes

**Comment by thinxer** [comment]
Hi there, I've merged the code and made several changes. The code is currently at: https://github.com/thinxer/tornado-proxy-server/tree/styling

Please try and see if the code styling issues remain.

**Comment by chenfengyuan** [comment]
Hi, nice work. I suppose this issue is fixed now.

**Pull request merged**
